GET http://localhost:5000/user

###
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "fullname": "Ananda Affan F",
    "NIM": "1301194171",
    "major": "Informatika",
    "faculty": "Informatika",
    "year": "2019",
    "phoneNumber": "08132616333",
    "homeAddress": "Jakarta",
    "email": "affanaaa@gmail.com",
    "password": "111222333",
    "confirmPassword": "111222333"
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "adminla@gmail.com",
    "password": "Adminaaaaaa"
}

###

POST http://localhost:5000/user/login
Content-Type: application/json
{
    "email": "Admin@gmail.com",
    "password": "Admin"
}
###
GET  http://localhost:5000/borrower
Content-Type: application/json

{
    
}

###
DELETE http://localhost:5000/category/deleteCategory/61058de11ce8932124677e73
Content-Type: application/json 

{

}
### 
POST http://localhost:5000/category/61058df29c209b214cbeb5db
Content-Type: application/json
{
    "categoryName": "Affan Ganteng"
}